plugins:
  push_notifications_enabled:
    default: false
    client: true
  push_notifications_prompt:
    default: false
    client: true
  vapid_public_key_bytes:
    default: ''
    client: true
    hidden: true
  vapid_public_key:
    default: ''
    hidden: true
  vapid_private_key:
    default: ''
    hidden: true
